### ISSUE TITLE
NeuroElf

### ISSUE THREAD

**Issue by igorkagan** [PRIME-RE/prime-re.github.io#11]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            | NeuroElf                                          |    
| **Authors**         | Jochen Weber                                                      |
| **Description**     | NeuroElf is a powerful Matlab-based toolbox for working with neuroimaging data |
| **Documentation**   | http://neuroelf.net/ |
| **Link**            | http://neuroelf.net/      |
| **Language**        | MATLAB               |
| **Publication**     | http://neuroelf.net/ |
| **Communication**   |  https://github.com/neuroelf/neuroelf-matlab   |
| **Restrictions**    | http://neuroelf.net/wiki/doku.php?id=neuroelf_license   |
    
    
- [ ] **Do NOT include this resource in periodic mailings about new resources on PRIME-RE**

**Comment by pcklink** [comment]
Added! Thanks for submitting. I created a new resource category on PRIME-RE called 'versatile tools' and listed it there. I don't feel it fits specifically under one of the 'pipelines' subgroups and the 'software packages' is more of a very minimal list of links to the big packages like FSL/AFNI/Freesurfer etc. I hope this is ok. If you'd like to have it listed elsewhere, let me know.
