### ISSUE TITLE
MR Comparative Anatomy Toolbox (Mr Cat)

### ISSUE THREAD

**Issue by neuroecology** [PRIME-RE/prime-re.github.io#13]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| MR Comparative Anatomy Toolbox (MrCat)            | > replace this with a name for your resource <                                          |    
| Rogier B. Mars, Lennart Verhagen, and the members and collaborators of the Cognitive Neuroecology Lab        | > replace this with author names <                                                      |
| A collection of tools for processing of multi-species neuroimaging data     | > replace this with a brief description of your resource <                              |
| **Documentation**   | > [replace this with a link to more extensive documentation](http://link-to-docs.com) < |
| www.neuroecologylab.org            | > [replace this with a link to your resource](http://link-to-resource.com) <            |
| shell, matlab        | > replace with language (python, shell, matlab, etc) your resource uses <               |
| http://www.rbmars.dds.nl/pubs/Mars2016NBR.pdf, among others     | > [replace this with a link to a related publication](http://link-to-publication.com) < |
| **Communication**   | > replace this with a means for communication <                                         |
| **Restrictions**    | > replace this with potential usage restrictions <                                      |
| structural/fMRI/diffusion        | > template/atlas/versatile/structural/fMRI/diffusion <                                  |
  
    
- [ ] **Do NOT include this resource in periodic mailings about new resources on PRIME-RE** 

## Instructions     
Please fill out the table above as completely as possible, i.e. replace the complete str `> .... <` with your information. 
Then submit it as a new issue and tag the issue with all applicable (yellow) categorical tags to specify what type of resource you are contributing.
We will use this table and these tags to add your resource to the main list.    

#### Name
Provide a name for your resource. Try to make it a bit descriptive, but as long as it as not incredibly offensive, we will allow it.    

#### Authors 
Who wrote the resource or deserves to be credited? This would be a good place to list them.

#### Description 
Tell the community what it is that your resource does. Keep it concise (a few lines).

#### Documentation
Does your resource include instructions on how to use it, and if so, where? 
This can be a hyperlink, or you can simply state that it can be found through the main link (e.g., because it's in a GitHub ReadMe.md).
Jupyter Notebooks or richly annotated scripts would be great, but any documentation would be great. 

#### Link
Provide a link to the resource. This can be a link to a GitHub repository, website, or shared file. 
If you don't already have your resource hosted somewhere and would like to have it hosted on this GitHub, 
tell us and provide us with a link to the resource (Dropbox, Google Drive, WeTransfer, etc)

#### Language
What language (e.g., python, shell, matlab, etc) is your resource in? This will help people to look at solutions in languages they are familiar with first.
We will accept anything. 

#### Associated publications (if available)
If your resource is a published method, you can link to the paper here.

#### Communication
How can a potential user get in contact with the submitter/author of the resource? 
Is there a Slack or Mattermost channel? Can issues be opened on a GitHub repo? Is there an email adress?
If you want to submit your resource 'as-is' and not offer any means for communication you can also mention that.

#### Restrictions
Are there any limitations for how the analysis method can be used (e.g., citation or acknowledgement required, etc)?

#### Category
What is the most suitable category to list your resource under?

**Comment by pcklink** [comment]
Included! Thanks for submitting!
