### ISSUE TITLE
<UNet model for skull stripping and brain masks of PRIME-DE>

### ISSUE THREAD

**Issue by TingsterX** [PRIME-RE/prime-re.github.io#14]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            |  UNet model for skull stripping and brain masks of anatomical images from PRIME-DE                                           |    
| **Authors**         | Xindi Wang, Ting Xu                                                      |
| **Description**     | The preprocessed brain masks of T1w images for all macaque monkeys from PRIME-DE. A convolutional network - UNet model was used to generate the brain mask for T1w images. The UNet model was initially trained in a large human sample and upgraded with a few macaque data. With a small macaque training sample (N=1-2), the UNet model achieves a decent performance of brain extraction with a minimal processing time (GPU: ~20s, CPU: 2-10 min). |
| **Documentation**   | [UNet model on PRIME-DE](https://github.com/TingsterX/PRIME-DE/tree/master/BrainExtraction) |
| **Link**            | [UNet model](https://github.com/to-be-release), [code](https://github.com/to-be-release), [preprocessed brain masks](https://github.com/to-be-release)        |
| **Language**        | python                |
| **Publication**     | [In prepartion](https://github.com/to-be-release) |
| **Communication**   |GitHub repo: email: ting.xu @childmind.org                                         |
| **Restrictions**    | GNU                                      |
| **Category**        | Brain extraction tool, preprocessed data  |
  
    
- [ ] **Do NOT include this resource in periodic mailings about new resources on PRIME-RE**

**Comment by pcklink** [comment]
Thanks Ting! I added it to the structural pipelines for now, but maybe we need to revise our categories at some point...
