### ISSUE TITLE
Logos for contributed resources

### ISSUE THREAD

**Issue by niksirbi** [PRIME-RE/prime-re.github.io#15]
Should we include an image option in the contributed template? We could ask for a logo of a specific format/resolution to make its integration on our website easier. It's only a cosmetic issue, but I think it will make the site look much better.

**Comment by pcklink** [comment]
Sure, go ahead and implement it. It is set up right now to minimise overhead for maintainers, but I have no objection if it can be done in a straightforward way. MAybe you can make a mock-up page to show what it would look like (e.g., pipelines_structural_wip.md)?

**Comment by niksirbi** [comment]
OK, I will see what I can do over the next days

**Comment by pcklink** [comment]
Doesn't seem necessary. Efforts are better directed at other issues or improvements.
