### ISSUE TITLE
<NMT 2.0 Templates (NIMH Macaque Template - version 2.0)>

### ISSUE THREAD

**Issue by messinga** [PRIME-RE/prime-re.github.io#17]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            | > NMT 2.0 Templates (NIMH Macaque Template - version 2.0) <                                          |    
| **Authors**         | > Adam Messinger, Benjamin Jung, Jakob Seidlitz, Paul Taylor, Daniel Glen <                                                      |
| **Description**     | > A collection of volumetric templates of the rhesus macaque created by nonlinear averaging of T1-weighted anatomical MRIs from multiple adult monkeys.  Surface files are included. The NMT 2.0 provides increased flexibility in macaque group analysis by providing symmetric and asymmetric templates. Both templates are available with an expanded, full head field of view.  The templates are available in both AC-PC orientation and in Horsley-Clarke stereotaxic orientation. Updates to the templates include:  an improved mapping of the D99 atlas, improved brain masking and normalization, and files that are defined in a common template space (NMT space), using the short data type for improved storage efficiency. <                              |
| **Documentation**   | > TBD< |
| **Link**            | > TBD <            |
| **Language**        | > Volumetric files are in NIFTI (.nii) format, while surface files are in GIFTI (.gii) format.  Alignment and brainmasking scripts (@animal_warper) are packaged with AFNI. Processing script rely on ANTs and shell scripting. <               |
| **Publication**     | > TBD < |
| **Communication**   | > Through the GitHub repo or via email to Dr. Adam Messinger: Adam.Messinger@nih.gov <                                         |
| **Restrictions**    | > Usage requires citation of this article: TBD <                                      |
| **Category**        | > template, atlas <                                  |
  
    
- [ ] **Do NOT include this resource in periodic mailings about new resources on PRIME-RE** 

## Instructions     
Please fill out the table above as completely as possible, i.e. replace the complete str `> .... <` with your information. 
Then submit it as a new issue and tag the issue with all applicable (yellow) categorical tags to specify what type of resource you are contributing.
We will use this table and these tags to add your resource to the main list.    

#### Name
Provide a name for your resource. Try to make it a bit descriptive, but as long as it as not incredibly offensive, we will allow it.    

#### Authors 
Who wrote the resource or deserves to be credited? This would be a good place to list them.

#### Description 
Tell the community what it is that your resource does. Keep it concise (a few lines).

#### Documentation
Does your resource include instructions on how to use it, and if so, where? 
This can be a hyperlink, or you can simply state that it can be found through the main link (e.g., because it's in a GitHub ReadMe.md).
Jupyter Notebooks or richly annotated scripts would be great, but any documentation would be great. 

#### Link
Provide a link to the resource. This can be a link to a GitHub repository, website, or shared file. 
If you don't already have your resource hosted somewhere and would like to have it hosted on this GitHub, 
tell us and provide us with a link to the resource (Dropbox, Google Drive, WeTransfer, etc)

#### Language
What language (e.g., python, shell, matlab, etc) is your resource in? This will help people to look at solutions in languages they are familiar with first.
We will accept anything. 

#### Associated publications (if available)
If your resource is a published method, you can link to the paper here.

#### Communication
How can a potential user get in contact with the submitter/author of the resource? 
Is there a Slack or Mattermost channel? Can issues be opened on a GitHub repo? Is there an email adress?
If you want to submit your resource 'as-is' and not offer any means for communication you can also mention that.

#### Restrictions
Are there any limitations for how the analysis method can be used (e.g., citation or acknowledgement required, etc)?

#### Category
What is the most suitable category to list your resource under?

**Comment by pcklink** [comment]
Included! Thanks!
