### ISSUE TITLE
<AFNI's @animal_warper>

### ISSUE THREAD

**Issue by messinga** [PRIME-RE/prime-re.github.io#18]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            | > @animal_warper AFNI command <                                          |    
| **Authors**         | >  Daniel Glen,  Paul Taylor, Adam Messinger, Benjamin Jung, Jakob Seidlitz <                                                      |
| **Description**     | > Nonlinearly aligns an MRI dataset to a template.  The reverse transformation can be used to produce a skullstripped (brain-only) version of the native scan, segmentation/atlas info in the native space, and surfaces for each atlas region. The computed transformations between the anatomical scan and the template is provided for use with FMRI pipeline tools like afni_proc.py. <                              |
| **Documentation**   | > https://afni.nimh.nih.gov/pub/dist/doc/program_help/@animal_warper.html  < |
| **Link**            | > https://afni.nimh.nih.gov/  <            |
| **Language**        | >  tcsh, python, C, AFNI <               |
| **Publication**     | > TBD < |
| **Communication**   | > AFNI message board - https://afni.nimh.nih.gov/afni/community/board/list.php?1 <                                         |
| **Restrictions**    | > no usage restrictions <                                      |
| **Category**        | > structural <                                  |
  
    
- [ ] **Do NOT include this resource in periodic mailings about new resources on PRIME-RE** 

## Instructions     
Please fill out the table above as completely as possible, i.e. replace the complete str `> .... <` with your information. 
Then submit it as a new issue and tag the issue with all applicable (yellow) categorical tags to specify what type of resource you are contributing.
We will use this table and these tags to add your resource to the main list.    

#### Name
Provide a name for your resource. Try to make it a bit descriptive, but as long as it as not incredibly offensive, we will allow it.    

#### Authors 
Who wrote the resource or deserves to be credited? This would be a good place to list them.

#### Description 
Tell the community what it is that your resource does. Keep it concise (a few lines).

#### Documentation
Does your resource include instructions on how to use it, and if so, where? 
This can be a hyperlink, or you can simply state that it can be found through the main link (e.g., because it's in a GitHub ReadMe.md).
Jupyter Notebooks or richly annotated scripts would be great, but any documentation would be great. 

#### Link
Provide a link to the resource. This can be a link to a GitHub repository, website, or shared file. 
If you don't already have your resource hosted somewhere and would like to have it hosted on this GitHub, 
tell us and provide us with a link to the resource (Dropbox, Google Drive, WeTransfer, etc)

#### Language
What language (e.g., python, shell, matlab, etc) is your resource in? This will help people to look at solutions in languages they are familiar with first.
We will accept anything. 

#### Associated publications (if available)
If your resource is a published method, you can link to the paper here.

#### Communication
How can a potential user get in contact with the submitter/author of the resource? 
Is there a Slack or Mattermost channel? Can issues be opened on a GitHub repo? Is there an email adress?
If you want to submit your resource 'as-is' and not offer any means for communication you can also mention that.

#### Restrictions
Are there any limitations for how the analysis method can be used (e.g., citation or acknowledgement required, etc)?

#### Category
What is the most suitable category to list your resource under?

**Comment by pcklink** [comment]
Included! Thanks!
