### ISSUE TITLE
Improve web design

### ISSUE THREAD

**Issue by niksirbi** [PRIME-RE/prime-re.github.io#21]
Improving looks, navigation, UI in general.

**Comment by pcklink** [comment]
Let's put this on hold for a while. We're working on the paper and want to focus on ease-of-use and functionality for now. While making it more appealing could definitely help broader usage, a major overhaul would be a bit distracting at the moment.

**Comment by niksirbi** [comment]
Agreed, so far I haven't found the time for it anyway

**Comment by afni-dglen** [comment]
The PRIME-RE wikipage has "Custom Footer" that's editable by anyone arriving on the page.
https://github.com/PRIME-RE/prime-re.github.io/wiki

**Comment by pcklink** [comment]
We initially opened up the wiki to everyone. Now that there's substantial content we may be a little bit more protective. I've restricted write access to team members and will wrote a little note telling people that can submit update proposal or request access by raising an issue.

**Comment by afni-dglen** [comment]
Looks good.
