### ISSUE TITLE
Marmoset Brain Connectivity Atlas

### ISSUE THREAD

**Issue by pmajka** [PRIME-RE/prime-re.github.io#25]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            | Marmoset Brain Connectivity Atlas                                          |    
| **Authors**         | The project is lead by Piotr Majka of the Laboratory of Neuroinformatics at the Nencki Institute of Experimental Biology (Poland) and prof. Marcello Rosa at Monash University (Australia). For full list of contributors, please visit http://www.marmosetbrain.org/about.                                                       |
| **Description**     | The Marmoset Brain Connectivity Atlas allows for the exploration of a growing collection of retrograde tracer injections in the marmoset neocortex. Data obtained in different animals are registered to a [common stereotaxic space](http://www.marmosetbrain.org/reference) of Paxinos et al. (2012) atlas, and the resource incorporates tools for quantitative analyses. In particular, the results can be downloaded in 3D volume format in a template space which allows for ready comparisons to topologies acquired by MRI.                              |
| **Documentation**   | Portal’s application programming interface is available at http://analytics.marmosetbrain.org/wiki/api and http://analytics.marmosetbrain.org/wiki/database.  |
| **Link**            | http://www.marmosetbrain.org/            |
| **Language**        | The portal is implemented in JavaScript, Python, and CSS / HTML. The source code of both components of the http://marmosetbrain.org is released under the GPL license (see: https://github.com/Neuroinflab/marmosetbrain.org and https://github.com/Neuroinflab/analysis.Marmosetbrain.org).               |
| **Publication**     | [Open access resource for cellular-resolution analyses of corticocortical connectivity in the marmoset monkey.](http://doi.org/10.1038/s41467-020-14858-0) and [Towards a comprehensive atlas of cortical connections in a primate brain: Mapping tracer injection studies of the common marmoset into a reference digital template](http://doi.org/10.1002/cne.24023).|
| **Communication**   | Piotr Majka (p.majka@nencki.edu.pl)   |
| **Restrictions**    | Material made public on the Marmoset Brain Connectivity Atlas is licensed under Creative Commons Attribution-ShareAlike 4.0 (CC-BY-SA) License. You are free to share (copy and redistribute) and adapt (remix, transform, and build upon) the marmoset-related material in any medium or format as long as you attribute the Marmoset Brain Connectivity Atlas and provide a link to the two URLs the Marmoset Brain Connectivity Atlas and the CC license). If you adapt the material, you must distribute your contributions under the same license as the original.                                      |
| **Category**        | Templates and Atlases > Marmoset                                |
  
Table entry
Template: 3D Paxinos et al. (2012)
Species: C. jacchus
Resolution (mm3): 0.04×0.5×0.04 mm3
With atlas: Cortical areas of the Paxinos et al., (2012)
Volume format: NIFTI
Surface format: N/A
Links: http://www.marmosetbrain.org/reference
    
- [ ] **Do NOT include this resource in periodic mailings about new resources on PRIME-RE** 

## Instructions     
Please fill out the table above as completely as possible, i.e. replace the complete str `> .... <` with your information. 
Then submit it as a new issue and tag the issue with all applicable (yellow) categorical tags to specify what type of resource you are contributing.
We will use this table and these tags to add your resource to the main list.    

#### Name
Provide a name for your resource. Try to make it a bit descriptive, but as long as it as not incredibly offensive, we will allow it.    

#### Authors 
Who wrote the resource or deserves to be credited? This would be a good place to list them.

#### Description 
Tell the community what it is that your resource does. Keep it concise (a few lines).

#### Documentation
Does your resource include instructions on how to use it, and if so, where? 
This can be a hyperlink, or you can simply state that it can be found through the main link (e.g., because it's in a GitHub ReadMe.md).
Jupyter Notebooks or richly annotated scripts would be great, but any documentation would be great. 

#### Link
Provide a link to the resource. This can be a link to a GitHub repository, website, or shared file. 
If you don't already have your resource hosted somewhere and would like to have it hosted on this GitHub, 
tell us and provide us with a link to the resource (Dropbox, Google Drive, WeTransfer, etc)

#### Language
What language (e.g., python, shell, matlab, etc) is your resource in? This will help people to look at solutions in languages they are familiar with first.
We will accept anything. 

#### Associated publications (if available)
If your resource is a published method, you can link to the paper here.

#### Communication
How can a potential user get in contact with the submitter/author of the resource? 
Is there a Slack or Mattermost channel? Can issues be opened on a GitHub repo? Is there an email adress?
If you want to submit your resource 'as-is' and not offer any means for communication you can also mention that.

#### Restrictions
Are there any limitations for how the analysis method can be used (e.g., citation or acknowledgement required, etc)?

#### Category
What is the most suitable category to list your resource under?

**Comment by pcklink** [comment]
Added. Thanks!
