### ISSUE TITLE
Nencki–Monash Template

### ISSUE THREAD

**Issue by pmajka** [PRIME-RE/prime-re.github.io#26]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            |Nencki-Monash Template                                          |    
| **Authors**         | The template has been created in collaboration between the Laboratory of Neuroinformatics at the Nencki Institute of Experimental Biology (Poland) and prof. Marcello Rosa Laboratory at Monash University (Australia).                                                      |
| **Description**     | The Nencki-Monash (NM) template represents a morphological average of 20 brains of young adult individuals, obtained by 3D reconstructions generated from Nissl-stained serial sections. The template combines combines the main advantages of histology-based atlases with features associated with MRI-based templates. It is also accompanied with spatial transformations to other popular marmoset brain templates, thus enabling integration with magnetic resonance imaging (MRI) and tracer-based connectivity data.                              |
| **Documentation**   | The documentation and examples are available within individual datasets available for download via http://www.marmosetbrain.org/nencki_monash_template |
| **Link**            | http://www.marmosetbrain.org/nencki_monash_template            |
| **Language**        | N/A               |
| **Publication**     | [Histology-based average template of the marmoset cortex with probabilistic localization of cytoarchitectural areas](https://doi.org/10.1101/2020.04.10.036632) |
| **Communication**   | Piotr Majka (p.majka@nencki.edu.pl)                                         |
| **Restrictions**    | Nencki-Monash Template is licensed under Creative Commons Attribution-ShareAlike 4.0 (CC-BY-SA) License. You are free to share (copy and redistribute) and adapt (remix, transform, and build upon) the marmoset-related material in any medium or format as long as you attribute the Nencki-Monash Template and cite the relevant publication. If you adapt the material, you must distribute your contributions under the same license as the original.                                      |
| **Category**        | Templates and Atlases > Marmoset                                  |
  

Table entry
Template: Nencki-Monash
Species: C. jacchus
Resolution (mm3): 0.05
With atlas: Cortical areas of the Paxinos et al., (2012)
Volume format: NIFTI
Surface format: N/A
Links: http://www.marmosetbrain.org/nencki_monash_template
    
- [ ] **Do NOT include this resource in periodic mailings about new resources on PRIME-RE** 

## Instructions     
Please fill out the table above as completely as possible, i.e. replace the complete str `> .... <` with your information. 
Then submit it as a new issue and tag the issue with all applicable (yellow) categorical tags to specify what type of resource you are contributing.
We will use this table and these tags to add your resource to the main list.    

#### Name
Provide a name for your resource. Try to make it a bit descriptive, but as long as it as not incredibly offensive, we will allow it.    

#### Authors 
Who wrote the resource or deserves to be credited? This would be a good place to list them.

#### Description 
Tell the community what it is that your resource does. Keep it concise (a few lines).

#### Documentation
Does your resource include instructions on how to use it, and if so, where? 
This can be a hyperlink, or you can simply state that it can be found through the main link (e.g., because it's in a GitHub ReadMe.md).
Jupyter Notebooks or richly annotated scripts would be great, but any documentation would be great. 

#### Link
Provide a link to the resource. This can be a link to a GitHub repository, website, or shared file. 
If you don't already have your resource hosted somewhere and would like to have it hosted on this GitHub, 
tell us and provide us with a link to the resource (Dropbox, Google Drive, WeTransfer, etc)

#### Language
What language (e.g., python, shell, matlab, etc) is your resource in? This will help people to look at solutions in languages they are familiar with first.
We will accept anything. 

#### Associated publications (if available)
If your resource is a published method, you can link to the paper here.

#### Communication
How can a potential user get in contact with the submitter/author of the resource? 
Is there a Slack or Mattermost channel? Can issues be opened on a GitHub repo? Is there an email adress?
If you want to submit your resource 'as-is' and not offer any means for communication you can also mention that.

#### Restrictions
Are there any limitations for how the analysis method can be used (e.g., citation or acknowledgement required, etc)?

#### Category
What is the most suitable category to list your resource under?

**Comment by pcklink** [comment]
Added. Thanks!
