### ISSUE TITLE
Neurovault.org <Resource Name>

### ISSUE THREAD

**Issue by asfox** [PRIME-RE/prime-re.github.io#27]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            | > Neurovault.org <                                          |    
| **Authors**         | > Fox AS & Gorgolewski KJ <                                                      |
| **Description**     | > The method for optimally sharing voxelwise data from NHP neuroimaging studies remains unclear. To address this issue, Fox and colleagues have adapted the Neurovault.org resource (Gorgolewski et al., 2015), which is commonly used to share human neuroimaging data, to other species, including rhesus monkeys. To complement within-manuscript reporting (e.g. location of peak-activations), researchers can now upload any voxelwise images aligned to NMT-template space, including unthresohlded statistical maps, atlases, and ROIs to Neurovault.org by specifying their species-specific template. Collections of voxelwise analyses can be linked to publication DOIs to appropriately credit researchers, and will ultimately facilitate meta-analyses, and other large-scale data-scientific efforts, such as cross-species comparisons. 
 <                              |
| **Documentation**   | > https://neurovault.org/FAQ < |
| **Link**            | > https://neurovault.org/ <            |
| **Publication**     | > Gorgolewski KJ, Varoquaux G, Rivera G, Schwartz Y, Ghosh SS, Maumet C, Sochat VV, Nichols TE, Poldrack RA, Poline J-B, Yarkoni T and Margulies DS (2015) NeuroVault.org: a web-based repository for collecting and sharing unthresholded statistical maps of the brain. Front. Neuroinform. 9:8. doi: 10.3389/fninf.2015.00008 < |
| **Communication**   | > dfox@ucdavis.edu <                                         |
| **Category**        | > data sharing <                                  |

**Comment by pcklink** [comment]
Added!
