### ISSUE TITLE
<precon_all>

### ISSUE THREAD

**Issue by recoveringyank** [PRIME-RE/prime-re.github.io#31]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            | precon_all                                       |    
| **Authors**         | R. Austin Benn, Ting Xu                                                    |
| **Description**     | precon_all is an anatomical surface reconstruction pipeline that can be used with Non-Human Primates, and other large animals including pigs, dogs, and potentially many more. The pipeline can be easily modified to work on most species with a reasonable T1 image by simply providing 5 masks. The pipeline provides both free surfer and HCP compatible outputs in native image space. Group average surfaces and spherical registration templates can also be created within the precon_all framework.                             |
| **Documentation**   |  https://github.com/recoveringyank/precon_all  |
| **Link**            |  https://github.com/recoveringyank/precon_all             |
| **Language**        | shell              |
| **Publication**     | In Preparation |
| **Communication**   | rabbenn@cnic.es                                         |
| **Restrictions**    | None                                      |
| **Category**        | Structural MRI                                |
  
    
- [ ] **Do NOT include this resource in periodic mailings about new resources on PRIME-RE**

**Comment by pcklink** [comment]
Added! Thanks!
