### ISSUE TITLE
C-PAC: The Configurable Pipeline for the Analysis of Connectomes

### ISSUE THREAD

**Issue by sgiavasis** [PRIME-RE/prime-re.github.io#32]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            | C-PAC: The Configurable Pipeline for the Analysis of Connectomes                                          |    
| **Authors**         | Steven Giavasis, Cameron Craddock, Michael Milham                                                      |
| **Description**     | The Configurable Pipeline for the Analysis of Connectomes (C-PAC) is a configurable, open-source, Nipype-based, automated processing pipeline for resting state functional MRI (R-fMRI) data, for use by both novice and expert users. It is designed and tested for use with human data (all ages), as well as with non-human primate and rodent data.                              |
| **Documentation**   | [http://fcp-indi.github.io/](http://fcp-indi.github.io/)  |
| **Link**            | [Quick-Start - pull a container](http://fcp-indi.github.io/docs/user/quick.html)            |
| **Language**        | Python               |
| **Publication**     | [Towards Automated Analysis of Connectomes: The Configurable Pipeline for the Analysis of Connectomes (C-PAC)](https://www.frontiersin.org/10.3389/conf.fninf.2013.09.00042/event_abstract) |
| **Communication**   | [C-PAC Forum](https://groups.google.com/forum/#!forum/cpax_forum)                                         |
| **Restrictions**    | None                                      |
| **Category**        | versatile, structural, fMRI                                  |

**Comment by pcklink** [comment]
Added!
