### ISSUE TITLE
Juna.Chimp

### ISSUE THREAD

**Issue by viko18** [PRIME-RE/prime-re.github.io#49]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            | Juna.Chimp Templates & Davi130 parcellation                                         |    
| **Authors**         | Sam Vickery, William D Hopkins, Chet C Sherwood, Steven J Schapiro, Jona Fischer , Robert D Latzman, Svenja Caspers, Christian Gaser, Simon B Eickhoff, Robert Dahnke , Felix Hoffstaedter                                                    |
| **Description**     | We provide a chimpanzee structural T1w template, chimpanzee tissue probabilty maps (TPM), and a manual macroanatomical parcellation of the chimpanzee brain which can be interactively viewed through a web viewer. Additionaly, we supply an exemplar preprocessing pipeline using CAT12 with the required templates including a chimpanzee geodesic shooting template.                       |
| **Documentation**   | https://github.com/viko18/JunaChimp |
| **Link**            | http://junachimp.inm7.de/           |
| **Language**        | Matlab               |
| **Publication**     | https://elifesciences.org/articles/60136 |
| **Communication**   | email address: s.vickery@fz-juelich.de and/or open an issue at https://github.com/viko18/JunaChimp                                    |
| **Restrictions**    | Please cite our publication if you use this resource                                     |
| **Category**        | structural template, preprocessing templates, and macroanatomical parcellation                                 |
  
** Please check the applicable boxes**    
- [ x] All required ethical approval (human/animal) for the development of this resource was obtained  
- [ ] No ethical approval (human/animal) was required for the development of this resource      
- [ ] Do NOT include this resource in periodic mailings about new resources on PRIME-RE 

## Instructions     
Please fill out the table above as completely as possible, i.e. replace the complete str `> .... <` with your information. 
Then submit it as a new issue and tag the issue with all applicable (yellow) categorical tags to specify what type of resource you are contributing.
We will use this table and these tags to add your resource to the main list.    

#### Name
Provide a name for your resource. Try to make it a bit descriptive, but as long as it as not incredibly offensive, we will allow it.    

#### Authors 
Who wrote the resource or deserves to be credited? This would be a good place to list them.

#### Description 
Tell the community what it is that your resource does. Keep it concise (a few lines).

#### Documentation
Does your resource include instructions on how to use it, and if so, where? 
This can be a hyperlink, or you can simply state that it can be found through the main link (e.g., because it's in a GitHub ReadMe.md).
Jupyter Notebooks or richly annotated scripts would be great, but any documentation would be great. 

#### Link
Provide a link to the resource. This can be a link to a GitHub repository, website, or shared file. 
If you don't already have your resource hosted somewhere and would like to have it hosted on this GitHub, 
tell us and provide us with a link to the resource (Dropbox, Google Drive, WeTransfer, etc)

#### Language
What language (e.g., python, shell, matlab, etc) is your resource in? This will help people to look at solutions in languages they are familiar with first.
We will accept anything. 

#### Associated publications (if available)
If your resource is a published method, you can link to the paper here.

#### Communication
How can a potential user get in contact with the submitter/author of the resource? 
Is there a Slack or Mattermost channel? Can issues be opened on a GitHub repo? Is there an email adress?
If you want to submit your resource 'as-is' and not offer any means for communication you can also mention that.

#### Restrictions
Are there any limitations for how the analysis method can be used (e.g., citation or acknowledgement required, etc)?

#### Category
What is the most suitable category to list your resource under?

#### Checkboxes
Please indicate whether ethical approval was acquired for activities related to the development of this resource, or whether this wasn't necessary. Also, indicate if you do not want your resource advertised in sparsely sent updates from the PRIME-RE team to the community.

**Comment by pcklink** [comment]
Added at https://prime-re.github.io/templates_and_atlases_chimpansee.html available through https://prime-re.github.io/templates_and_atlases.

Thanks you for contributing to open NHP neuroimaging resource sharing!

**Comment by viko18** [comment]
Added Nifti to description, fixed some typo's and the link should be chimpanZee not chimpanSee. Thanks.

**Comment by pcklink** [comment]
Fixed.
