### ISSUE TITLE
MR Monitoring Resource (PRIME-MRM)

### ISSUE THREAD

**Issue by cipetkov** [PRIME-RE/prime-re.github.io#51]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            | PRIME-MRM: MRI monitoring of monkeys in neuroscience    |    
| **Authors**         | F Balezeau, J Nacef, Y Kikuchi, F Schneider, F Rocchi, RS Muers, R Fernandez-Palacios O’Connor, C Blau, B Wilson, RC Saunders, M Howard III, A Thiele, TD Griffiths, *CI Petkov & *K Murphy (* joint senior authors) |
| **Description**     | Information from Magnetic Resonance Imaging (MRI) is useful for diagnosis and treatment management of human neurological patients. MRI monitoring might also prove useful for non-human animals involved in neuroscience research provided that MRI is available and feasible and that there are no MRI contra-indications precluding scanning. We establish an MRI Monitoring (PRIME-MRM) resource within the PRIMatE Data Exchange (PRIME-DE) and encourage submissions by the scientific community to grow the resource and the evidence base on MRI monitoring. The community is also encouraged to contribute to PRIME-RE to gow the resource exchange linked to PRIME-MRM.                              |
| **Documentation**   | For more information, please see the PRIME-DE contributions linked under PRIME-MRM for the data. The forthcoming paper (Balezeau et al.) provides further information on how to contribute, how MRI monitoring could be useful and how to grow the evidence base including quantification in relation to normative data on PRIME-DE. For the initial cases contributed, we show MRI quantification of internal controls in relation to treatment steps and comparisons with normative data in typical monkeys drawn from PRIME-DE. MRI monitoring can assist in precise and early diagnosis of cerebral events and can be useful for visualising, treating and quantifying treatment response. The scientific community is encouraged to grow the PRIME-MRM resource with other cases and larger samples to further assess and increase the evidence base on the benefits of MRI monitoring of primates, complementing the animals’ clinical monitoring and treatment regime. We also suggest in the paper a set of basic scans that can serve as a basic scan toolkit, as well as a more extensive set of scans as needed. We will be compiling a list of veterinary, radiology or clinicians that could be consulted or provide further guidance. We encourage a brief animal history and any diagnostic information to be included as meta data on PRIME-DE contributions. |
| **Link**            | https://fcon_1000.projects.nitrc.org/indi/indiPRIME.html   |
| **Publication**     | forthcoming, currently under minor revision ... |
| **Communication**   | chris.petkov@ncl.ac.uk or fabien.balezeau@ncl.ac.uk; Please feel free to contact us if you have questions.                                          |
| **Restrictions**    | No restrictions  |
| **Category**        | PRIME-DE resource  |
  
** Please check the applicable boxes**    
- [X] All required ethical approvals contributing to the development of this resource were obtained (see paper)  
- [ ] No ethical approval (human/animal) was required for the development of this resource      
- [ ] Do NOT include this resource in periodic mailings about new resources on PRIME-RE 

## Instructions     
Please fill out the table above as completely as possible, i.e. replace the complete str `> .... <` with your information. 
Then submit it as a new issue and tag the issue with all applicable (yellow) categorical tags to specify what type of resource you are contributing.
We will use this table and these tags to add your resource to the main list.    

#### Name
Provide a name for your resource. Try to make it a bit descriptive, but as long as it as not incredibly offensive, we will allow it.    

#### Authors 
Who wrote the resource or deserves to be credited? This would be a good place to list them.

#### Description 
Tell the community what it is that your resource does. Keep it concise (a few lines).

#### Documentation
Does your resource include instructions on how to use it, and if so, where? 
This can be a hyperlink, or you can simply state that it can be found through the main link (e.g., because it's in a GitHub ReadMe.md).
Jupyter Notebooks or richly annotated scripts would be great, but any documentation would be great. 

#### Link
Provide a link to the resource. This can be a link to a GitHub repository, website, or shared file. 
If you don't already have your resource hosted somewhere and would like to have it hosted on this GitHub, 
tell us and provide us with a link to the resource (Dropbox, Google Drive, WeTransfer, etc)

#### Language
What language (e.g., python, shell, matlab, etc) is your resource in? This will help people to look at solutions in languages they are familiar with first.
We will accept anything. 

#### Associated publications (if available)
If your resource is a published method, you can link to the paper here.

#### Communication
How can a potential user get in contact with the submitter/author of the resource? 
Is there a Slack or Mattermost channel? Can issues be opened on a GitHub repo? Is there an email adress?
If you want to submit your resource 'as-is' and not offer any means for communication you can also mention that.

#### Restrictions
Are there any limitations for how the analysis method can be used (e.g., citation or acknowledgement required, etc)?

#### Category
What is the most suitable category to list your resource under?

#### Checkboxes
Please indicate whether ethical approval was acquired for activities related to the development of this resource, or whether this wasn't necessary. Also, indicate if you do not want your resource advertised in sparsely sent updates from the PRIME-RE team to the community.

**Comment by cipetkov** [comment]
Hello Chris, Here is the suggested PRIME-RE information on the MR Monitoring resource. Let me know if you need any corrections (or see typos). I'll update the paper link as soon as we have it. I'm also inspred by the meeting we had on Friday and will provide a few updates to this information going forward, so let me know what would be the best way to update. Thank you! -Chris P.

**Comment by pcklink** [comment]
Added at [https://prime-re.github.io/hardware_and_protocols/prime-mrm.html](https://prime-re.github.io/hardware_and_protocols/prime-mrm.html), referenced from the [protocols list](https://prime-re.github.io/hardware).

**Comment by cipetkov** [comment]
Thanks Chris. I'll send you a message here with updates as they are needed. What is your view on how others can link to this in PRIME-RE? For instance other projects not related to protocols might #51 is that the idea?
