### ISSUE TITLE
<Cross-species alignment (macaque-human)>

### ISSUE THREAD

**Issue by TingsterX** [PRIME-RE/prime-re.github.io#55]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            | Cross-species alignment (macaque-human)                                           |    
| **Authors**         | Ting Xu, Karl-Heinz Nenning                                                       |
| **Description**     | This repo includes 1) landmarks for the macaque-human alignment, 2) functional phylogenetic map (functional connectivity homology index) between macaque and human, 3) evolutional surface area expansion (macaque-to-human), 4) cross-species parcellations (human-to-macaque: Glasser2016, Yeo2011, Broadmann parcellations on the macaque surfaces; macaque-to-human: Markov2014 and Broadmann parcellations on human HCP surface, and 5) human (Human Connectome Project [HCP]) and macaque (MacaqueYerkes19) surfaces                              |
| **Documentation**   | [replace this with a link to more extensive documentation](http://link-to-docs.com)  |
| **Link**            | [https://github.com/TingsterX/alignment_macaque-human](https://github.com/TingsterX/alignment_macaque-human)            |
| **Language**        | shell, workbench                |
| **Publication**     | [Xu, Nenning et al., 2020](https://www.sciencedirect.com/science/article/pii/S1053811920308326)  |
| **Communication**   | [GitHub profile](https://github.com/TingsterX) or [email](ting.xu@childmind.org)                                         |
| **Restrictions**    | Please cite the above publication and the github repo https://github.com/TingsterX/alignment_macaque-human                                       |
| **Category**        | template/atlas/cross-species-comparison <                                |
  
** Please check the applicable boxes**    
- [x] All required ethical approval (human/animal) for the development of this resource was obtained  
- [ ] No ethical approval (human/animal) was required for the development of this resource      
- [ ] Do NOT include this resource in periodic mailings about new resources on PRIME-RE 

## Instructions     
Please fill out the table above as completely as possible, i.e. replace the complete str `> .... <` with your information. 
Then submit it as a new issue and tag the issue with all applicable (yellow) categorical tags to specify what type of resource you are contributing.
We will use this table and these tags to add your resource to the main list.    

#### Name
Provide a name for your resource. Try to make it a bit descriptive, but as long as it as not incredibly offensive, we will allow it.    

#### Authors 
Who wrote the resource or deserves to be credited? This would be a good place to list them.

#### Description 
Tell the community what it is that your resource does. Keep it concise (a few lines).

#### Documentation
Does your resource include instructions on how to use it, and if so, where? 
This can be a hyperlink, or you can simply state that it can be found through the main link (e.g., because it's in a GitHub ReadMe.md).
Jupyter Notebooks or richly annotated scripts would be great, but any documentation would be great. 

#### Link
Provide a link to the resource. This can be a link to a GitHub repository, website, or shared file. 
If you don't already have your resource hosted somewhere and would like to have it hosted on this GitHub, 
tell us and provide us with a link to the resource (Dropbox, Google Drive, WeTransfer, etc)

#### Language
What language (e.g., python, shell, matlab, etc) is your resource in? This will help people to look at solutions in languages they are familiar with first.
We will accept anything. 

#### Associated publications (if available)
If your resource is a published method, you can link to the paper here.

#### Communication
How can a potential user get in contact with the submitter/author of the resource? 
Is there a Slack or Mattermost channel? Can issues be opened on a GitHub repo? Is there an email adress?
If you want to submit your resource 'as-is' and not offer any means for communication you can also mention that.

#### Restrictions
Are there any limitations for how the analysis method can be used (e.g., citation or acknowledgement required, etc)?

#### Category
What is the most suitable category to list your resource under?

#### Checkboxes
Please indicate whether ethical approval was acquired for activities related to the development of this resource, or whether this wasn't necessary. Also, indicate if you do not want your resource advertised in sparsely sent updates from the PRIME-RE team to the community.

**Comment by pcklink** [comment]
Thanks. This opens up a new 'cross-species' resource category! I added it to the repo/page and also crosslinked from the templates/atlasses page.
