### ISSUE TITLE
Structural, diffusion and rs-functional MRI in Macaque Monkeys

### ISSUE THREAD

**Issue by vanessadcc** [PRIME-RE/prime-re.github.io#61]
## Resource info table    

| **Name**            | Structural, diffusion and rs-functional MRI in Macaque Monkeys                                         |    
| **Authors**         | Vanessa De Castro, Benoit Cottereau and Jean-Baptiste Durand                                                    |
| **Description**     | This dataset contains unprocessed structural, diffusion and rs-functional MRI data acquired in 3 female rhesus macaques. Each monkey underwent multiple sessions. For each session they were lightly anesthetized. The animals were installed in sphinx position with their head restrained by a head-post. Whole-brain images were acquired on a 3 Tesla clinical MR scanner (Philips Achieva).                              |
| **Link**            |    https://openneuro.org/datasets/ds003989/versions/1.0.0        |
| **Publication**     | https://doi.org/10.1093/cercor/bhaa301 |
| **Communication**   | vanessa.decastro@cnrs.fr; jbdurand@cnrs.fr                                         |
| **Restrictions**    | citation required                                  |
| **Category**        | structural/fMRI/diffusion                                   |
  
** Please check the applicable boxes**    
- [X] All required ethical approval (human/animal) for the development of this resource was obtained  
- [ ] No ethical approval (human/animal) was required for the development of this resource      
- [ ] Do NOT include this resource in periodic mailings about new resources on PRIME-RE

**Comment by pcklink** [comment]
Included. Thank you for contributing to more open science and data sharing!
