### ISSUE TITLE
<Resource Name>

### ISSUE THREAD

**Issue by TaoZhong11** [PRIME-RE/prime-re.github.io#63]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            | > UNC-LPBR 4D Cynomolgus Macaque Atlases from Birth to 48 Months <                                          |    
| **Authors**         | > Tao Zhong, Jingkuan Wei, Kunhua Wu, Liangjun Chen, Fenqiang Zhao, Yuchen Pei, Ya Wang, Hongjiang Zhang, Zhengwang Wu, Ying Huang, Tengfei Li, Li Wang, Yongchang Chen, Weizhi Ji, Yu Zhang, Gang Li, Yuyu Niu <                                                      |
| **Description**     | > We construct a comprehensive set of longitudinal brain atlases and associated tissue probability maps (gray matter, white matter, and cerebrospinal fluid) with a totally of 12 time-points from birth to 4 years of age (i.e., 1, 2, 3, 4, 5, 6, 9, 12, 18, 24, 36, and 48 months of age) based on 175 longitudinal structural MRI scans from 39 typically-developing cynomolgus macaques. To facilitate region-based analysis using the atlases, we also provide two popular hierarchy parcellations from NMT v2, i.e., cortical hierarchy maps (6 levels) and subcortical hierarchy maps (6 levels), on these longitudinal macaque brain atlases.  <                              |
| **Documentation**   | >https://www.nitrc.org/projects/cyno_4d_atlas/< |
| **Link**            | >https://www.nitrc.org/projects/cyno_4d_atlas/ <            |
| **Language**        | > NIFTI (.nii.gz) format <               |
| **Publication**     | > https://www.sciencedirect.com/science/article/pii/S1053811921010703 < |
| **Communication**   | > taozh2315@gmail.com <                                         |
| **Restrictions**    | >None <                                      |
| **Category**        | > template and atlas <                                  |
  
** Please check the applicable boxes**    
- [ ] All required ethical approval (human/animal) for the development of this resource was obtained  
- [ ] No ethical approval (human/animal) was required for the development of this resource      
- [ ] Do NOT include this resource in periodic mailings about new resources on PRIME-RE 

## Instructions     
Please fill out the table above as completely as possible, i.e. replace the complete str `> .... <` with your information. 
Then submit it as a new issue and tag the issue with all applicable (yellow) categorical tags to specify what type of resource you are contributing.
We will use this table and these tags to add your resource to the main list.    

#### Name
Provide a name for your resource. Try to make it a bit descriptive, but as long as it as not incredibly offensive, we will allow it.    

#### Authors 
Who wrote the resource or deserves to be credited? This would be a good place to list them.

#### Description 
Tell the community what it is that your resource does. Keep it concise (a few lines).

#### Documentation
Does your resource include instructions on how to use it, and if so, where? 
This can be a hyperlink, or you can simply state that it can be found through the main link (e.g., because it's in a GitHub ReadMe.md).
Jupyter Notebooks or richly annotated scripts would be great, but any documentation would be great. 

#### Link
Provide a link to the resource. This can be a link to a GitHub repository, website, or shared file. 
If you don't already have your resource hosted somewhere and would like to have it hosted on this GitHub, 
tell us and provide us with a link to the resource (Dropbox, Google Drive, WeTransfer, etc)

#### Language
What language (e.g., python, shell, matlab, etc) is your resource in? This will help people to look at solutions in languages they are familiar with first.
We will accept anything. 

#### Associated publications (if available)
If your resource is a published method, you can link to the paper here.

#### Communication
How can a potential user get in contact with the submitter/author of the resource? 
Is there a Slack or Mattermost channel? Can issues be opened on a GitHub repo? Is there an email adress?
If you want to submit your resource 'as-is' and not offer any means for communication you can also mention that.

#### Restrictions
Are there any limitations for how the analysis method can be used (e.g., citation or acknowledgement required, etc)?

#### Category
What is the most suitable category to list your resource under?

#### Checkboxes
Please indicate whether ethical approval was acquired for activities related to the development of this resource, or whether this wasn't necessary. Also, indicate if you do not want your resource advertised in sparsely sent updates from the PRIME-RE team to the community.

**Comment by pcklink** [comment]
Added.
