### ISSUE TITLE
Metadata behavior & environment

### ISSUE THREAD

**Issue by collinepoirier** [PRIME-RE/prime-re.github.io#69]
Hi Chris,
Could you please adjust the description of this project as including genotyping? In the text, you might want to add that we are interested in pedigree information for heritability studies and blood/tissue sample for genotyping purpose.
Thanks.
Best wishes,
Colline

**Comment by pcklink** [comment]
I added genotyping to the title in the collab-page and the discussion board. I also added your line to the description on the collab-page. If you want to explain more, feel free to open the thread on the Discussion Board with a post with more information.
