### ISSUE TITLE
Macapype

### ISSUE THREAD

**Issue by julfou81** [PRIME-RE/prime-re.github.io#7]
# Macapype

## Pipeline Description
Segmentation Tools For Monkey Brains

## Contributors
Kep kee Loh, David Meunier, Bastien Cagna, Julien Sein, Régis Trapeau
@ [Institut de Neurosciences de la Timone, Marseille, France](http://www.int.univ-amu.fr/?lang=en)

## Dependencies
What different types of people could contribute?

## Link to your code
[GitHub](https://github.com/BastienCagna/macapype)  

## Communication
Link to the communication channel for your project. You can, for example, create a [slack channel](https://brainhack-slack-invite.herokuapp.com/) for your project inside the Brainhack slack community, and include a slack badge [![slack_brainhack_3](https://user-images.githubusercontent.com/6297454/47951457-5b37b780-df61-11e8-9d77-7b5a4c7af875.png)](https://brainhack-slack-invite.herokuapp.com/) to invite people to Brainhack slack, where they can then find and join your channel.  
Or create a community on [gitter](https://gitter.im/) and link to the chat by including a Gitter badge linking to your community 
[![Gitter chat](https://badges.gitter.im/gitterHQ/gitter.png)](https://gitter.im/yourRoom/Lobby#)

**Comment by pcklink** [comment]
Macapype has been added. Closing this.
