### ISSUE TITLE
 Brain/MINDS Data Portal <Resource Name>

### ISSUE THREAD

**Issue by FPa-riken** [PRIME-RE/prime-re.github.io#79]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            | Brain/MINDS Data Portal |    
| **Authors**         | [Brain/MINDS project](https://brainminds.jp/en)’s participants. |
| **Description**     | The [Brain/MINDS Data Portal](https://dataportal.brainminds.jp/) has been launched for sharing the data and knowledge being produced in the [Brain/MINDS project](https://brainminds.jp/en), Japan’s Brain Mapping Project. <br>The unique appeal of the Brain/MINDS project is its focus on mapping the brain of a small new world monkey, the common marmoset (Callithrix jacchus). This is important because research on the non-human primate brain is essential for understanding the human brain and for developing knowledge-based strategies for the diagnosis and treatment of psychiatric and neurological disorders.<br>The Data Portal aims to provide integrated knowledge for public use and original data for open research and collaboration. |
| **Documentation**   | https://dataportal.brainminds.jp/about |
| **Link**            | https://dataportal.brainminds.jp |
| **Language**        | Website in English |
| **Publication**     | https://brainminds.jp/en/publication |
| **Communication**   | CAU-Contact ([cau-contact@ml.riken.jp](mailto:cau-contact@ml.riken.jp))  |
| **Restrictions**    | The conditions for data usage are described separately for each dataset on their respective landing pages.  |
| **Category**        | Data Sharing |
  
** Please check the applicable boxes**    
- [X] All required ethical approval (human/animal) for the development of this resource was obtained  
- [ ] No ethical approval (human/animal) was required for the development of this resource      
- [ ] Do NOT include this resource in periodic mailings about new resources on PRIME-RE

**Comment by FPa-riken** [comment]
Thanks for handling our submission quickly!

However we noticed a small typo in name published on [PRIME-RE resource page](https://prime-re.github.io/data_sharing.html#brainminds-data-portal) 😄 :
![image](https://github.com/PRIME-RE/prime-re.github.io/assets/64643044/e5e4db28-6f7f-4794-93dd-cd8ab2cd53ed)

Actually, the correct name for this resource is **Brain/MINDS Data Portal**, not to be confused with **Brain/MINDS**, the overall project itself that has its own distinct website (https://brainminds.jp).

Could you please update the **Link** label accordingly? Thank you.

**Comment by pcklink** [comment]
Done!
