### ISSUE TITLE
Move general knowledge section to wiki section of GitHub

### ISSUE THREAD

**Issue by julfou81** [PRIME-RE/prime-re.github.io#8]
What do you think about putting the description part of the main page to the wiki section of the GitHub?

Things like spatial preprocessing, functional preprocessing, etc...

**Comment by niksirbi** [comment]
I think it makes sense. So your idea is to have only the atlases/tools/pipelines on the main page and move everything else to wiki, right? I am in favor of it, but it would be nice to add a button/link next to the topic name on the main page that leads you to the corresponding wiki page.
E.g. sth like this:
2. Structural preprocessing
[Read more about this](link to wiki page)
Pipelines:
a. macapype etc...

**Comment by julfou81** [comment]
I agree, I will see how to make an hyperlink from the main page to the wiki page. I will work on it by the end of the week.

**Comment by pcklink** [comment]
The Wiki is now still referenced from the main header menu, but it's a bit incomplete. Is anyone willing to work on it? In my personal view, I think working on it in Wiki-form makes sense, but if it reaches a point where it's basically a minimal generic instruction of the kind of (pre)processing steps involved in NHP MRI analysis, we can move it to a page or several pages and have it part of the main website instead.

**Comment by pcklink** [comment]
Kep Kee will work on converting the Tutorials document that was created by a group of people into the Wiki so it gets populated. The hope is than that the community will fine-tune and expand since the wiki is not not meant as the definitive guide to NHP neuroimaging analysis but rather an initial guide for the confused.

**Comment by pcklink** [comment]
Wiki is online, I think we can close this.
