### ISSUE TITLE
Brain/MINDS Marmoset Reference Atlas Set (BMA)  <Resource Name>

### ISSUE THREAD

**Issue by FPa-riken** [PRIME-RE/prime-re.github.io#80]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            | Brain/MINDS Marmoset Reference Atlas Set (BMA) |    
| **Authors**         | The resource development is lead by the [Connectome Analysis Unit](https://cau.riken.jp/), Integrative Computational Brain Science Collaboration Division, [RIKEN Center for Brain Science](https://www.riken.jp/en/research/labs/cbs/), Japan.<br><br>Full list of contributors:<br>Alexander Woodward, Tsutomu Hashikawa, Masahide Maeda, Takaaki Kaneko, Keigo Hikishima, Atsushi Iriki, Hideyuki Okano, Yoko Yamaguchi, Rui Gong, Ken Nakae, Junichi Hata, Shin Ishii, Hiroshi Abe, Toshiki Tani, Frederic Papazian, Hiromi Masuko, Takuto Okuno, Tetsuo Yamamori, Noritaka Ichinohe.  |
| **Description**     | The Brain/MINDS Marmoset Reference Atlas Set (BMA) provide 3D brain atlases for the common marmoset:<br>  *  **BMA 2017**: ex-vivo multi-modal Nissl & MRI 3D atlas.<br>  * **BMA 2019**: builds on previous work and adds a population average ex-vivo MRI T2WI contrast and cortical flat maps.<br>  * **BMA 2023**: a population-based brain atlas constructed from N=10 cortical region parcellations. It includes a symmetric standard template space created from 92 MRI T2WI scans. |
| **Documentation**   | https://dataportal.brainminds.jp/atlas-package-download-main-page |
| **Link**            | https://dataportal.brainminds.jp/atlas-package-download-main-page |
| **Language**        | n/a |
| **Publication**     | Woodward, A., Hashikawa, T., Maeda, M. Kaneko, T., Hikishima, K., Iriki, A., Okano, H., Yamaguchi, Y. The Brain/MINDS 3D digital marmoset brain atlas. _Sci Data_ **5**, 180009 (2018). https://doi.org/10.1038/sdata.2018.9 |
| **Communication**   | CAU-Contact ([cau-contact@ml.riken.jp](mailto:cau-contact@ml.riken.jp)) |
| **Restrictions**    | This work is licensed under a [Creative Commons Attribution 4.0 International License (CC BY 4.0)](http://creativecommons.org/licenses/by/4.0/). |
| **Category**        | Templates and Atlases > Marmoset |
  
** Please check the applicable boxes**    
- [X] All required ethical approval (human/animal) for the development of this resource was obtained  
- [ ] No ethical approval (human/animal) was required for the development of this resource      
- [ ] Do NOT include this resource in periodic mailings about new resources on PRIME-RE

**Comment by FPa-riken** [comment]
Just noticed that on the [PRIME-RE resource page](https://prime-re.github.io/templates_and_atlases_marmoset.html#brainminds-marmoset-reference-atlas-set-bma), in the **Link** field, url initial letter is missing from the `href` value:

![image](https://github.com/PRIME-RE/prime-re.github.io/assets/64643044/48701e3b-7794-4a3c-9a28-b3322cf9396b)

Could you please correct it? Thanks.

**Comment by pcklink** [comment]
fixed
