### ISSUE TITLE
Pypreclin

### ISSUE THREAD

**Issue by Tasserie** [PRIME-RE/prime-re.github.io#9]
**Name:** 
_Pypreclin_, automatic Python preclinical pipeline for monkey fMRI preprocessing
**Authors:** 
Jordy TASSERIE, Antoine GRIGIS, Lynn Uhrig, Morgan Dupont, Alexis Amadon and Béchir JARRAYA. 
**Description & language:** 
_Pypreclin_ is a Python code available on GitHub, on the Python Package Index (PyPI) for easy installation and upgrading, and has been made available as a Singularity container. 
**Documentation & links:**
[Github](https://github.com/neurospin/pypreclin)
[Python  Package  Index  (PyPI)](https://pypi.org/project/pypreclin)
[Singularity  container  ](http://biodev.cea.fr/pypreclin/pypreclin-ubuntu.simg)
**Publication:**
Please cite the related publication,
Tasserie J, Grigis A, Uhrig L, Dupont M, Amadon A, Jarraya B.Neuroimage. 2019 Nov 16:116353. doi: 10.1016/j.neuroimage.2019.116353. PMID:31743789
[PubMed](https://www.ncbi.nlm.nih.gov/pubmed/31743789)
[Journal website](https://www.sciencedirect.com/science/article/pii/S1053811919309449?via%3Dihub)

**Comment by pcklink** [comment]
Thanks for submitting this! It may take us a while to get it up but we appreciate the contribution!

**Comment by niksirbi** [comment]
Thanks for submitting! The info has been added to the webpage https://prime-re.github.io/#fmri
